name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile and run tests on robot code
        run: ./gradlew build
  spotless:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew :spotlessApply
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Auto-format code
  submodule:
    runs-on: ubuntu-latest
    needs: [build, spotless]
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Extract
        env:
          SRC_FOLDER_PATH: 'src/main/java/org/team2342/lib'
          TARGET_BRANCH: 'submodule'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git fetch origin "$TARGET_BRANCH"
          git checkout "$TARGET_BRANCH"

          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          git checkout ${GITHUB_REF##*/} -- "$SRC_FOLDER_PATH"
          mv "$SRC_FOLDER_PATH"/* .
          rm -rf src/

          git add -A
          git diff-index --quiet HEAD || git commit -am "Extract library"
          git push origin "$TARGET_BRANCH"
